name: directory-listing
on: [push]

# based on update from 2025+ workarounds here:
# https://github.com/antocuni/files2/blob/4ec2e2eec178bc9395960ed458c482eb4e57b605/.github/workflows/workflow.yml

jobs:
  deploy:
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main     # or different branch

      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: items      # dir to generate index

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'      # upload generated folder

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
